### ISSUE TITLE
Greek language model won't install

### ISSUE THREAD

**Issue by gmarkop** [eellak/gsoc2018-spacy#5]
## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by gmarkop** [comment]
I am trying to install the greek language model (Ubuntu 18.04) according to the documentation with:

python3 -m spacy download el_core_web_sm

and I receive following message:

No compatible model found for 'el_core_web_sm' (spaCy v2.0.18).

I have also tried 'python3 -m spacy download el' with the same response.

Any suggestions would be much appreciated. Thank you in advance!

**Comment by mgogoulos** [comment]
Confirm models can't be installed. @giannisdaras can you have a look?

**Comment by giannisdaras** [comment]
Hello. Thanks for reporting that. The issue is already known. Truth is that greek models are not yet uploaded in the stable spaCy version, but are indeed uploaded in the `spacy-nightly` version of spaCy. So, I would suggest installing `spacy-nightly` with `pip install spacy-nightly` and then download the Greek models with <del>`spacy download el_web_news_md`</del> `spacy download el_core_news_md`

Let me know if you found any trouble with that!

**Comment by gmarkop** [comment]
Thank you for your replies. Unfortunately, after I've installed `spacy-nightly` and tried `spacy download el_web_news_md` I got the message:
> No compatible model found for 'el_web_news_md' (spaCy v2.1.0a7).

**Comment by giannisdaras** [comment]
Sorry, typo. Try again: `spacy download el_core_news_md`

**Comment by gmarkop** [comment]
Got it! Thank you very much! This will be very helpful for my introductory course in Computational Linguistics at the University. Congrats for your work on the greek language model and the complementary site `nlpbuddy.io`!

**Comment by giannisdaras** [comment]
Glad this is resolved and thanks for your kind words :)
I would really like to hear about the response of the students to this and whatever you may need again, I am at your disposal.
